### ISSUE TITLE
Awa static client fails to retry after registration failed timeout

### ISSUE THREAD

**Issue by rory-latchem-imgtec** [FlowM2M/AwaLWM2M#149]
If the Awa static client registers while the lwm2m server is down - it bootstraps OK then posts a registration request and hangs, with no retry on timeout. e.g.: the client log stops after the following:
...
 [INFO] [lwm2m_registration.c:137] Register with coap://127.0.0.1:5683
 [DEBUG] [lwm2m_registration.c:139] Register: POST coap://127.0.0.1:5683/rd?ep=AwaStaticClient1&lt=30&b=U

The same test with awa_clientd recovers properly when the server comes back up:
...
[INFO] Register with coap://127.0.0.1:5683
 [ERROR] Transaction Timed out
 [ERROR] Registration Failed! 504
 [INFO] Register with coap://127.0.0.1:5683
 [INFO] Registered with 127.0.0.1:5683

**Comment by david-antliff-imgtec** [comment]
Can you include the version number or git commit affected please?

**Comment by rory-latchem-imgtec** [comment]
v0.1.9

**Comment by rory-latchem-imgtec** [comment]
This was fixed in v0.2.0 (as part of previous commits for Erbium support)
