### ISSUE TITLE
Define custom objects when awa-serverd starts

### ISSUE THREAD

**Issue by thetoster** [FlowM2M/AwaLWM2M#200]
It would be nice to have a config file into which I can put list of my custom IPSO objects with resources. So when server start after crash/reboot it will have those objects/resources predefined. This will reduce need to call awa-server-define after starting server.

**Comment by david-antliff-imgtec** [comment]
The architecture is designed to support application-specific object definition through the use of the API or the Awa Tools. For example, a simple bash script could be used to define a set of IPSO objects, and this script can be run after the server has been started.

However we are considering adding support for custom objects to the **client** daemon startup, as there is currently no way to define objects in the client before it connects to the server, and it would be useful for the client to have the correct set of object definitions prior to registration, to help eliminate unnecessary server work when new definitions are added later.

**Comment by david-antliff-imgtec** [comment]
Version 0.2.0 should include support for "Object Definition Files", which are XML files that describe object/resource definitions. Both client and server daemon will support loading zero, one or more of these files at start-up, before any IPC or CoAP network traffic occurs. Default values for mandatory resources can be specified too, with the caveat that strings will need to be base64-encoded.

We intend to include an example/template for standard objects.
