### ISSUE TITLE
bootstrap configuration file load fail

### ISSUE THREAD

**Issue by dmazzer** [FlowM2M/AwaLWM2M#276]
I'm trying the following configuration file for the bootstrap server:

```
ServerURI=coap://192.168.30.100:5683
SecurityMode=0
ServerID=1
HoldOffTime=10
ShortServerID=1
Binding=U
LifeTime=30
DisableTimeout=86400
DefaultMinimumPeriod=1
DefaultMaximumPeriod=-1
NotificationStoringWhenDisabledOrOffline=1
```

And the server is started this way:
`
$ ./awa_bootstrapd --port 15685 --config bootstrtap.conf
`

And I aways receive this message.
```
 [ERROR] [lwm2m_bootstrap.c:104] Configuration file load failed
 [ERROR] [lwm2m_bootstrap.c:247] Failed to initialise bootstrap config for server 0

```

There is any problem with the configuration file?
Tested with master and 0.2.3

**Comment by DavidAntliff** [comment]
@dmazzer the config file loading is still a bit primitive. You need to have:

```
PublicKey=[PublicKey]
SecretKey=[SecretKey]
```

These should be directly after the SecurityMode line.

The daemon should provide better error reporting, so I'll flag this as a bug to fix.

**Comment by cdewbery** [comment]
@dmazzer is your bootstrap.conf file really called "bootstrtap.conf" or was that just a typo in the report?

**Comment by delme-imgtec** [comment]
Also looking at ParseLine function potentially there was an empty (zero length) line in config file (maybe at end) ?

**Comment by dmazzer** [comment]
I confirm that my bootstrap.conf have empty lines.
Removing the empty lines solved the problem. 
Thank you.

**Comment by dmazzer** [comment]
And after the #282 it works with empty lines and without SecretKey and PublicKey.
