### ISSUE TITLE
Missing mail list or contact information

### ISSUE THREAD

**Issue by dmazzer** [FlowM2M/AwaLWM2M#278]
Hello,
I could not find information about a mail list for general _user_ questions about AwaLWM2M. 
What is the best way to contact community to place general user questions?
Thank you.

**Comment by boyvinall** [comment]
Hi,

We've recently setup a discourse forum for that kind of thing. It's a bit sparse at the moment, but we'll be answering on there. For Awa topics, you can post in https://forum.creatordev.io/c/creator-iot-framework/awa-lwm2m. We'll add something to the docs soon to point you over there too.

Hope this helps.  Feel free to reply here and let us know if something's amiss.

**Comment by dmazzer** [comment]
Hello @boyvinall,
Thank you to point me out this forum.
