### ISSUE TITLE
error messages while call to awa-server-explore

### ISSUE THREAD

**Issue by thetoster** [FlowM2M/AwaLWM2M#284]
When execution tool awa-server-explore I'm getting list of all defined objects/resources but:
1) every even line message "ResourceOperationToString table is wrong size!" is printed
2) every resource operation is returned as 'BAD OPERATION'

example of my screen dump:
Object: ID:3303 name:IPSO Temperature Sensor minInstances:0 maxInstances:10
ResourceOperationToString table is wrong size!
    Resource: ID:5712 name:Average Value in 24h type:Float            minInstances:1 maxInstances:1 operations:BAD OPERATION
ResourceOperationToString table is wrong size!
    Resource: ID:5711 name:Average Value in 12h type:Float            minInstances:1 maxInstances:1 operations:BAD OPERATION
ResourceOperationToString table is wrong size!

**Comment by datachi7d** [comment]
Which version are you using? I fixed a similar issue in #210

**Comment by thetoster** [comment]
Sorry I'm using old build 0.1.10, didn't verified against new one.

**Comment by DavidAntliff** [comment]
This was fixed in [0.2.1](https://github.com/FlowM2M/AwaLWM2M/releases/tag/0.2.1).
