### ISSUE TITLE
AwaClientSession_Connect fails with AwaError_IPCError when STDIN has been closed

### ISSUE THREAD

**Issue by dgell37** [FlowM2M/AwaLWM2M#288]
When writing a daemon that connects to awa-clientd, if STDIN is closed then AwaClientSession_Connect returns the error code, AwaError_IPCError.

If I close STDIN and leave STDOUT and STDERR open the I get the following output;
[ipc.c:157] Success: Could not create UDP Socket
[session_common.c:510] AwaError_IPCError: Channel missing

**Comment by cheekyhalf** [comment]
Looks like you need to reopen the file descriptors pointing at /dev/null.
Adding the following after your close() calls fixes your issue.

int fd;

fd = open("/dev/null",O_RDWR, 0);

if (fd != -1) 
{   
  dup2 (fd, STDIN_FILENO);
  dup2 (fd, STDOUT_FILENO);
  dup2 (fd, STDERR_FILENO);
  
  if (fd > 2)
  close (fd);
}

See section 4 of this http://codingfreak.blogspot.com/2012/03/daemon-izing-process-in-linux.html

You could also use daemon() to save yourself a lot of this forking work.
