### ISSUE TITLE
Block transfer support

### ISSUE THREAD

**Issue by wbranski** [FlowM2M/AwaLWM2M#292]
Hello everyone!

Simple question:

Does the Awa library support  the Large Object transfer? In other words does tne Awa library 
support a coap block transfer for transferring  objects larger then single message size?

Best Regards 

WB

**Comment by seank-img** [comment]
Hi WB,

There is no support for block transfers - this requires design and implementation from the CoAP layer up to the API. It is a tricky problem to solve for the Awa API - how to provide large amounts of data through the IPC mechanism. The Awa Static API could handle the problem easily, each block request could be passed through to the application directly. However with Awa API it would be more tricky considering there's an IPC - it could use the same approach or have the application provide all the data at once.

In terms on the API do you have any ideas around providing the data for large resources?

**Comment by boyvinall** [comment]
I'm going to close this one, since there's a separate issue for implementing it.
