### ISSUE TITLE
incorrect pointer checking

### ISSUE THREAD

**Issue by tjobanpu** [FlowM2M/AwaLWM2M#293]
Found a potential bug in the code, the pointer in the below code check will always be true.
Line: 279 -  **_char path[URL_PATH_SIZE] = {0};_**
File: button_led_controller.c
Line: 288-  **_if (path != NULL)_**
This is because "path" is a local character array, 

should this be 
**_if (path[0] != NULL)_**

because in the file "api/src/path.c" , the first element of the path is set to NULL if things go wrong?
Line: 279
path[0] = '\0';

**Comment by DavidAntliff** [comment]
I'm not sure which file you are referring to, as there is no `button_led_controller.c` in the Awa repository.

The correct fix is probably `if (strnlen(path, URL_PATH_SIZE) != 0)`.

You are right however that `path` will never be NULL in the code you describe.

Aside: `NULL` (null pointer) is not the same as `\0` (null character) - they may have the same value (sometimes) but they are not interchangeable and relate to separate concepts.

**Comment by DavidAntliff** [comment]
I'm going to close this as invalid because it appears to relate to a file that is not in Awa.

**Comment by Duncan-Frazer-imgtec** [comment]
Hi tjobanpu - I think a better place for your question would be the button_led_controller repo over on the creatorkit organisation : https://github.com/CreatorKit/button-led-controller, or come over to the creator forum and discuss with the community : http://forum.creatordev.io. The button_led_controller app uses Awa but I don't believe the issue that you found is in the Awa code.
