### ISSUE TITLE
TinyDTLS library as PSK encrypt layer doesn't work with 32 byte keys.

### ISSUE THREAD

**Issue by thetoster** [FlowM2M/AwaLWM2M#297]
I've builded client on ci40 / linux with enabled tinyDTLS as a security layer. Then I tried to run awa_clientd with PSK identity/key generated on Device Server platform. But as a result I'm getting errors about wrong key sizes. Here is log from console:

> [INFO] Awa LWM2M Client, version 0.2.4
> [INFO]   Process ID     : 22396
> [INFO]   Endpoint name  : 'Awa Client'
> [INFO]   DTLS library   : TinyDTLS
> [INFO]   CoAP library   : Erbium
> [INFO]   CoAP port      : 6000
> [INFO]   IPC port       : 12345
> [INFO]   Address family : IPv4
> [INFO] Bind port: 6000
> [INFO] Try existing server entries
> [INFO] No servers are defined
> [INFO] Hold Off expired - attempt client-initiated bootstrap
> [INFO] Bootstrap with coaps://ds-mono.flowcloud.systems:15684/bs?ep=Awa Client
> [INFO] Coap request: coaps://ds-mono.flowcloud.systems:15684/bs?ep=Awa Client
> [WARN] cannot set psk -- buffer too small
> Nov 17 14:43:59 CRIT no psk key for session available
> Nov 17 14:43:59 WARN error in check_server_hellodone err: -592
> Nov 17 14:43:59 WARN error while handling handshake packet

**Comment by boyvinall** [comment]
Is this now resolved by #320  ?
