### ISSUE TITLE
Possible memory corruption in lwm2m_bootstrap.c

### ISSUE THREAD

**Issue by thetoster** [FlowM2M/AwaLWM2M#298]
In file [lwm2m_bootstrap.c](https://github.com/FlowM2M/AwaLWM2M/blob/master/core/src/client/lwm2m_bootstrap.c) it looks like it's possible to have memory overwritten. Variable `buffer` is defined as 128 bytes long, it's filled by method `Lwm2mCore_GetEndPointClientName`. From signature of this method it looks like whole buffer might be used, so we will have 128 bytes of data. Then this `buffer` is copied to variable `uriQuery` which is also 128 bytes long, however copy is done through `sprintf(uriQuery, "?ep=%s", buffer)` which might result in memory corruption.

**Comment by cheekyhalf** [comment]
A simple fix. A pull request would be appreciated :)
