### ISSUE TITLE
[PROPOSAL] - Add configuration file for daemons

### ISSUE THREAD

**Issue by francois-berder-imgtec** [FlowM2M/AwaLWM2M#314]
Hello,

Here is a proposal for configuring daemon using a file instead of specifying options on the command line.

## Description

Launching the client daemon can require many options. For instance, this project, https://github.com/CreatorDev/ci40-weather-station, asks people to run
this command to launch the client daemon:
```sh
$ awa_clientd --bootstrap coaps://deviceserver.flowcloud.systems:15684 --endPointName WeatherStationDevice --certificate=/root/certificate.crt --ipcPort 12345 -p7000 -d
```

It would be more readable if all these options are located in a file. Each line would set only one value in this format: ```name(=value)?```.
Using previous example, these options would be specified in a file config.cfg:
```
bootstrap=coaps://deviceserver.flowcloud.systems:15684
endPointName=WeatherStationDevice
certificate=/root/certificate.crt
ipcPort=12345
port=7000
daemonize
```

and the client would be launched in this way:

```sh
$ awa_clientd config.cfg
```

## Implementation

I suggest to add, in the main function of all daemons, the following logic:
```
if argc > 1 && argv[1] matches *.cfg
    override argc and argv with content from config file
```

And the parsing of the configuration file would be done in daemon/src/common/config.c. It would produce an array of strings, along with the number of strings in the array.
This would be written roughly in this way:
```c
/**
 * @param[in] filePath
 * @param[out] args 
 * @return negative number if an error occured, argc otherwise
 */
int ParseConfigurationFile(char *filePath, char **args)
{
    ret = 1
    open file in filePath
    n = number of non-empty lines

    for each line in file:
        if line is empty:
            skip
        name,value = match(line, "name(=value)?")
        args.append("--" + name)
        ret++    
        if value:
            args.append(value) 
            ret++

    return ret
}
```

**Comment by DavidAntliff** [comment]
Just curious - why was this closed?

**Comment by francois-berder-imgtec** [comment]
@DavidAntliff The option --factoryBootstrap=FILE is already doing most of what is currently suggested in this proposal.

**Comment by meowsqueak** [comment]
@francois-berder-imgtec true, for some options. Also, the systemd (or equivalent) mechanism can cover other options.
