### ISSUE TITLE
Daemonizing Awa client fails to connect with the device server

### ISSUE THREAD

**Issue by payalsarnot** [FlowM2M/AwaLWM2M#321]
I am using following command to start Awa client and connect it to my device server,
awa_clientd --bootstrap coaps://deviceserver.creatordev.io:15684 -s -c /root/certificate.crt --endPointName "weather_station" -d
Executing this command does not display any error but my ci40 client fails to be displayed in my Developer Console account.

Instead, if I use,
awa_clientd --bootstrap coaps://deviceserver.creatordev.io:15684 --endPointName WeatherStationDevice -s -c /etc/config/certificate.crt &
above command client is successfully created and displayed in the Developer Console account.

**Comment by boyvinall** [comment]
Hi @payalsarnot, think there must be something else going on here, as this works for other people. What log messages do you get in each case?

**Comment by cheekyhalf** [comment]
@payalsarnot you are using a different certificate in both these commands, not just adding the -d flag. Are you sure that isn't the issue?

**Comment by payalsarnot** [comment]
@boyvinall @cheekyhalf this is working for me now. Don't know what was the issue earlier. Thanks for help.
