### ISSUE TITLE
How different is this w.r.t. Leshan

### ISSUE THREAD

**Issue by nginxsantos** [FlowM2M/AwaLWM2M#323]
Hi,
How is this different than Leshan?  
Does this support external data store and clustering support too?

Regards, Santos

**Comment by ehirdoy** [comment]
I'm also quite interested in server scalability(==clustering support).
Any feedback for Santos's question would be really appreciated.

**Comment by boyvinall** [comment]
The Awa server is not designed for a horizontally-scaled, redundant deployment - so there's no support for clustering.  Currently, it's a single-threaded app which is mostly designed for either running on gateway devices and for test purposes.  For cloud-based deployments, you could take a look at our other project [github.com/CreatorDev/DeviceServer](https://github.com/CreatorDev/DeviceServer).  HTH.
