### ISSUE TITLE
Cannot bootstrap more than 5 clickers

### ISSUE THREAD

**Issue by mtusnio** [FlowM2M/AwaLWM2M#336]
Trying to bootstrap to a local Awa server on a Ci40 maxes out at 5 clickers. The data seems to be flowing through, however the server fails to respond properly to any bootstrap requests. After disabling the 5 clickers and enabling a 6th one it still wouldn't bootstrap.

Logs & dump attached
[awa_logs.tar.gz](https://github.com/FlowM2M/AwaLWM2M/files/748226/awa_logs.tar.gz)

**Comment by boyvinall** [comment]
I suspect this might be related to https://github.com/FlowM2M/AwaLWM2M/blob/master/core/src/common/network_abstraction_linux.c#L85

Will have to understand this a bit deeper to determine the complete solution, but it's probably worth increasing this value in your application.

**Comment by mtusnio** [comment]
That's done the trick, I've managed to go all the way up to 11.

**Comment by boyvinall** [comment]
Have ... a good time ... all the time.
